INSERT INTO WINE_TYPE VALUES(1, 'Riesling', 'Rose', 'Production');
INSERT INTO WINE_TYPE VALUES(2, 'Riesling', 'Rose', 'Distribution');
INSERT INTO WINE_TYPE VALUES(3, 'Riesling', 'Rose', 'Retail');
INSERT INTO WINE_TYPE VALUES(4,'Riesling','White','Production');
INSERT INTO WINE_TYPE VALUES(5,'Riesling','White','Distribution');
INSERT INTO WINE_TYPE VALUES(6,'Riesling','White','Retail');
INSERT INTO WINE_TYPE VALUES(7,'Riesling','Red','Production');
INSERT INTO WINE_TYPE VALUES(8,'Riesling','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(9,'Riesling','Red','Retail');
INSERT INTO WINE_TYPE VALUES(10,'Chardonnay','Rose','Production');
INSERT INTO WINE_TYPE VALUES(11,'Chardonnay','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(12,'Chardonnay','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(13,'Chardonnay','White','Production');
INSERT INTO WINE_TYPE VALUES(14,'Chardonnay','White','Distribution');
INSERT INTO WINE_TYPE VALUES(15,'Chardonnay','White','Retail');
INSERT INTO WINE_TYPE VALUES(16,'Chardonnay','Red','Production');
INSERT INTO WINE_TYPE VALUES(17,'Chardonnay','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(18,'Chardonnay','Red','Retail');
INSERT INTO WINE_TYPE VALUES(19,'Sauvignon Blanc','Rose','Production');
INSERT INTO WINE_TYPE VALUES(20,'Sauvignon Blanc','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(21,'Sauvignon Blanc','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(22,'Sauvignon Blanc','White','Production');
INSERT INTO WINE_TYPE VALUES(23,'Sauvignon Blanc','White','Distribution');
INSERT INTO WINE_TYPE VALUES(24,'Sauvignon Blanc','White','Retail');
INSERT INTO WINE_TYPE VALUES(25,'Sauvignon Blanc','Red','Production');
INSERT INTO WINE_TYPE VALUES(26,'Sauvignon Blanc','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(27,'Sauvignon Blanc','Red','Retail');
INSERT INTO WINE_TYPE VALUES(28,'Gewurztraminer','Rose','Production');
INSERT INTO WINE_TYPE VALUES(29,'Gewurztraminer','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(30,'Gewurztraminer','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(31,'Gewurztraminer','White','Production');
INSERT INTO WINE_TYPE VALUES(32,'Gewurztraminer','White','Distribution');
INSERT INTO WINE_TYPE VALUES(33,'Gewurztraminer','White','Retail');
INSERT INTO WINE_TYPE VALUES(34,'Gewurztraminer','Red','Production');
INSERT INTO WINE_TYPE VALUES(35,'Gewurztraminer','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(36,'Gewurztraminer','Red','Retail');
INSERT INTO WINE_TYPE VALUES(37,'Semillon','Rose','Production');
INSERT INTO WINE_TYPE VALUES(38,'Semillon','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(39,'Semillon','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(40,'Semillon','White','Production');
INSERT INTO WINE_TYPE VALUES(41,'Semillon','White','Distribution');
INSERT INTO WINE_TYPE VALUES(42,'Semillon','White','Retail');
INSERT INTO WINE_TYPE VALUES(43,'Semillon','Red','Production');
INSERT INTO WINE_TYPE VALUES(44,'Semillon','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(45,'Semillon','Red','Retail');
INSERT INTO WINE_TYPE VALUES(46,'Pinot Gris','Rose','Production');
INSERT INTO WINE_TYPE VALUES(47,'Pinot Gris','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(48,'Pinot Gris','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(49,'Pinot Gris','White','Production');
INSERT INTO WINE_TYPE VALUES(50,'Pinot Gris','White','Distribution');
INSERT INTO WINE_TYPE VALUES(51,'Pinot Gris','White','Retail');
INSERT INTO WINE_TYPE VALUES(52,'Pinot Gris','Red','Production');
INSERT INTO WINE_TYPE VALUES(53,'Pinot Gris','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(54,'Pinot Gris','Red','Retail');
INSERT INTO WINE_TYPE VALUES(55,'Viognier','Rose','Production');
INSERT INTO WINE_TYPE VALUES(56,'Viognier','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(57,'Viognier','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(58,'Viognier','White','Production');
INSERT INTO WINE_TYPE VALUES(59,'Viognier','White','Distribution');
INSERT INTO WINE_TYPE VALUES(60,'Viognier','White','Retail');
INSERT INTO WINE_TYPE VALUES(61,'Viognier','Red','Production');
INSERT INTO WINE_TYPE VALUES(62,'Viognier','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(63,'Viognier','Red','Retail');
INSERT INTO WINE_TYPE VALUES(64,'Chenin Blanc','Rose','Production');
INSERT INTO WINE_TYPE VALUES(65,'Chenin Blanc','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(66,'Chenin Blanc','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(67,'Chenin Blanc','White','Production');
INSERT INTO WINE_TYPE VALUES(68,'Chenin Blanc','White','Distribution');
INSERT INTO WINE_TYPE VALUES(69,'Chenin Blanc','White','Retail');
INSERT INTO WINE_TYPE VALUES(70,'Chenin Blanc','Red','Production');
INSERT INTO WINE_TYPE VALUES(71,'Chenin Blanc','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(72,'Chenin Blanc','Red','Retail');
INSERT INTO WINE_TYPE VALUES(73,'Muller-Thurgau','Rose','Production');
INSERT INTO WINE_TYPE VALUES(74,'Muller-Thurgau','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(75,'Muller-Thurgau','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(76,'Muller-Thurgau','White','Production');
INSERT INTO WINE_TYPE VALUES(77,'Muller-Thurgau','White','Distribution');
INSERT INTO WINE_TYPE VALUES(78,'Muller-Thurgau','White','Retail');
INSERT INTO WINE_TYPE VALUES(79,'Muller-Thurgau','Red','Production');
INSERT INTO WINE_TYPE VALUES(80,'Muller-Thurgau','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(81,'Muller-Thurgau','Red','Retail');
INSERT INTO WINE_TYPE VALUES(82,'Madeleine Angevine','Rose','Production');
INSERT INTO WINE_TYPE VALUES(83,'Madeleine Angevine','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(84,'Madeleine Angevine','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(85,'Madeleine Angevine','White','Production');
INSERT INTO WINE_TYPE VALUES(86,'Madeleine Angevine','White','Distribution');
INSERT INTO WINE_TYPE VALUES(87,'Madeleine Angevine','White','Retail');
INSERT INTO WINE_TYPE VALUES(88,'Madeleine Angevine','Red','Production');
INSERT INTO WINE_TYPE VALUES(89,'Madeleine Angevine','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(90,'Madeleine Angevine','Red','Retail');
INSERT INTO WINE_TYPE VALUES(91,'Siegerrebe','Rose','Production');
INSERT INTO WINE_TYPE VALUES(92,'Siegerrebe','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(93,'Siegerrebe','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(94,'Siegerrebe','White','Production');
INSERT INTO WINE_TYPE VALUES(95,'Siegerrebe','White','Distribution');
INSERT INTO WINE_TYPE VALUES(96,'Siegerrebe','White','Retail');
INSERT INTO WINE_TYPE VALUES(97,'Siegerrebe','Red','Production');
INSERT INTO WINE_TYPE VALUES(98,'Siegerrebe','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(99,'Siegerrebe','Red','Retail');
INSERT INTO WINE_TYPE VALUES(100,'Muscat Ottonel','Rose','Production');
INSERT INTO WINE_TYPE VALUES(101,'Muscat Ottonel','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(102,'Muscat Ottonel','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(103,'Muscat Ottonel','White','Production');
INSERT INTO WINE_TYPE VALUES(104,'Muscat Ottonel','White','Distribution');
INSERT INTO WINE_TYPE VALUES(105,'Muscat Ottonel','White','Retail');
INSERT INTO WINE_TYPE VALUES(106,'Muscat Ottonel','Red','Production');
INSERT INTO WINE_TYPE VALUES(107,'Muscat Ottonel','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(108,'Muscat Ottonel','Red','Retail');
INSERT INTO WINE_TYPE VALUES(109,'Orange Muscat','Rose','Production');
INSERT INTO WINE_TYPE VALUES(110,'Orange Muscat','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(111,'Orange Muscat','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(112,'Orange Muscat','White','Production');
INSERT INTO WINE_TYPE VALUES(113,'Orange Muscat','White','Distribution');
INSERT INTO WINE_TYPE VALUES(114,'Orange Muscat','White','Retail');
INSERT INTO WINE_TYPE VALUES(115,'Orange Muscat','Red','Production');
INSERT INTO WINE_TYPE VALUES(116,'Orange Muscat','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(117,'Orange Muscat','Red','Retail');
INSERT INTO WINE_TYPE VALUES(118,'Aligote','Rose','Production');
INSERT INTO WINE_TYPE VALUES(119,'Aligote','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(120,'Aligote','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(121,'Aligote','White','Production');
INSERT INTO WINE_TYPE VALUES(122,'Aligote','White','Distribution');
INSERT INTO WINE_TYPE VALUES(123,'Aligote','White','Retail');
INSERT INTO WINE_TYPE VALUES(124,'Aligote','Red','Production');
INSERT INTO WINE_TYPE VALUES(125,'Aligote','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(126,'Aligote','Red','Retail');
INSERT INTO WINE_TYPE VALUES(127,'Cabernet Sauvignon','Rose','Production');
INSERT INTO WINE_TYPE VALUES(128,'Cabernet Sauvignon','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(129,'Cabernet Sauvignon','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(130,'Cabernet Sauvignon','White','Production');
INSERT INTO WINE_TYPE VALUES(131,'Cabernet Sauvignon','White','Distribution');
INSERT INTO WINE_TYPE VALUES(132,'Cabernet Sauvignon','White','Retail');
INSERT INTO WINE_TYPE VALUES(133,'Cabernet Sauvignon','Red','Production');
INSERT INTO WINE_TYPE VALUES(134,'Cabernet Sauvignon','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(135,'Cabernet Sauvignon','Red','Retail');
INSERT INTO WINE_TYPE VALUES(136,'Merlot','Rose','Production');
INSERT INTO WINE_TYPE VALUES(137,'Merlot','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(138,'Merlot','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(139,'Merlot','White','Production');
INSERT INTO WINE_TYPE VALUES(140,'Merlot','White','Distribution');
INSERT INTO WINE_TYPE VALUES(141,'Merlot','White','Retail');
INSERT INTO WINE_TYPE VALUES(142,'Merlot','Red','Production');
INSERT INTO WINE_TYPE VALUES(143,'Merlot','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(144,'Merlot','Red','Retail');
INSERT INTO WINE_TYPE VALUES(145,'Syrah','Rose','Production');
INSERT INTO WINE_TYPE VALUES(146,'Syrah','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(147,'Syrah','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(148,'Syrah','White','Production');
INSERT INTO WINE_TYPE VALUES(149,'Syrah','White','Distribution');
INSERT INTO WINE_TYPE VALUES(150,'Syrah','White','Retail');
INSERT INTO WINE_TYPE VALUES(151,'Syrah','Red','Production');
INSERT INTO WINE_TYPE VALUES(152,'Syrah','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(153,'Syrah','Red','Retail');
INSERT INTO WINE_TYPE VALUES(154,'Cabernet Franc','Rose','Production');
INSERT INTO WINE_TYPE VALUES(155,'Cabernet Franc','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(156,'Cabernet Franc','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(157,'Cabernet Franc','White','Production');
INSERT INTO WINE_TYPE VALUES(158,'Cabernet Franc','White','Distribution');
INSERT INTO WINE_TYPE VALUES(159,'Cabernet Franc','White','Retail');
INSERT INTO WINE_TYPE VALUES(160,'Cabernet Franc','Red','Production');
INSERT INTO WINE_TYPE VALUES(161,'Cabernet Franc','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(162,'Cabernet Franc','Red','Retail');
INSERT INTO WINE_TYPE VALUES(163,'Malbec','Rose','Production');
INSERT INTO WINE_TYPE VALUES(164,'Malbec','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(165,'Malbec','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(166,'Malbec','White','Production');
INSERT INTO WINE_TYPE VALUES(167,'Malbec','White','Distribution');
INSERT INTO WINE_TYPE VALUES(168,'Malbec','White','Retail');
INSERT INTO WINE_TYPE VALUES(169,'Malbec','Red','Production');
INSERT INTO WINE_TYPE VALUES(170,'Malbec','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(171,'Malbec','Red','Retail');
INSERT INTO WINE_TYPE VALUES(172,'Pinot Noir','Rose','Production');
INSERT INTO WINE_TYPE VALUES(173,'Pinot Noir','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(174,'Pinot Noir','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(175,'Pinot Noir','White','Production');
INSERT INTO WINE_TYPE VALUES(176,'Pinot Noir','White','Distribution');
INSERT INTO WINE_TYPE VALUES(177,'Pinot Noir','White','Retail');
INSERT INTO WINE_TYPE VALUES(178,'Pinot Noir','Red','Production');
INSERT INTO WINE_TYPE VALUES(179,'Pinot Noir','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(180,'Pinot Noir','Red','Retail');
INSERT INTO WINE_TYPE VALUES(181,'Sangiovese','Rose','Production');
INSERT INTO WINE_TYPE VALUES(182,'Sangiovese','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(183,'Sangiovese','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(184,'Sangiovese','White','Production');
INSERT INTO WINE_TYPE VALUES(185,'Sangiovese','White','Distribution');
INSERT INTO WINE_TYPE VALUES(186,'Sangiovese','White','Retail');
INSERT INTO WINE_TYPE VALUES(187,'Sangiovese','Red','Production');
INSERT INTO WINE_TYPE VALUES(188,'Sangiovese','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(189,'Sangiovese','Red','Retail');
INSERT INTO WINE_TYPE VALUES(190,'Lemberger','Rose','Production');
INSERT INTO WINE_TYPE VALUES(191,'Lemberger','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(192,'Lemberger','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(193,'Lemberger','White','Production');
INSERT INTO WINE_TYPE VALUES(194,'Lemberger','White','Distribution');
INSERT INTO WINE_TYPE VALUES(195,'Lemberger','White','Retail');
INSERT INTO WINE_TYPE VALUES(196,'Lemberger','Red','Production');
INSERT INTO WINE_TYPE VALUES(197,'Lemberger','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(198,'Lemberger','Red','Retail');
INSERT INTO WINE_TYPE VALUES(199,'Grenache','Rose','Production');
INSERT INTO WINE_TYPE VALUES(200,'Grenache','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(201,'Grenache','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(202,'Grenache','White','Production');
INSERT INTO WINE_TYPE VALUES(203,'Grenache','White','Distribution');
INSERT INTO WINE_TYPE VALUES(204,'Grenache','White','Retail');
INSERT INTO WINE_TYPE VALUES(205,'Grenache','Red','Production');
INSERT INTO WINE_TYPE VALUES(206,'Grenache','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(207,'Grenache','Red','Retail');
INSERT INTO WINE_TYPE VALUES(208,'Zinfandel','Rose','Production');
INSERT INTO WINE_TYPE VALUES(209,'Zinfandel','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(210,'Zinfandel','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(211,'Zinfandel','White','Production');
INSERT INTO WINE_TYPE VALUES(212,'Zinfandel','White','Distribution');
INSERT INTO WINE_TYPE VALUES(213,'Zinfandel','White','Retail');
INSERT INTO WINE_TYPE VALUES(214,'Zinfandel','Red','Production');
INSERT INTO WINE_TYPE VALUES(215,'Zinfandel','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(216,'Zinfandel','Red','Retail');
INSERT INTO WINE_TYPE VALUES(217,'Barbera','Rose','Production');
INSERT INTO WINE_TYPE VALUES(218,'Barbera','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(219,'Barbera','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(220,'Barbera','White','Production');
INSERT INTO WINE_TYPE VALUES(221,'Barbera','White','Distribution');
INSERT INTO WINE_TYPE VALUES(222,'Barbera','White','Retail');
INSERT INTO WINE_TYPE VALUES(223,'Barbera','Red','Production');
INSERT INTO WINE_TYPE VALUES(224,'Barbera','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(225,'Barbera','Red','Retail');
INSERT INTO WINE_TYPE VALUES(226,'Petit Verdot','Rose','Production');
INSERT INTO WINE_TYPE VALUES(227,'Petit Verdot','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(228,'Petit Verdot','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(229,'Petit Verdot','White','Production');
INSERT INTO WINE_TYPE VALUES(230,'Petit Verdot','White','Distribution');
INSERT INTO WINE_TYPE VALUES(231,'Petit Verdot','White','Retail');
INSERT INTO WINE_TYPE VALUES(232,'Petit Verdot','Red','Production');
INSERT INTO WINE_TYPE VALUES(233,'Petit Verdot','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(234,'Petit Verdot','Red','Retail');
INSERT INTO WINE_TYPE VALUES(235,'Nebbiolo','Rose','Production');
INSERT INTO WINE_TYPE VALUES(236,'Nebbiolo','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(237,'Nebbiolo','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(238,'Nebbiolo','White','Production');
INSERT INTO WINE_TYPE VALUES(239,'Nebbiolo','White','Distribution');
INSERT INTO WINE_TYPE VALUES(240,'Nebbiolo','White','Retail');
INSERT INTO WINE_TYPE VALUES(241,'Nebbiolo','Red','Production');
INSERT INTO WINE_TYPE VALUES(242,'Nebbiolo','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(243,'Nebbiolo','Red','Retail');
INSERT INTO WINE_TYPE VALUES(244,'Mourvdre','Rose','Production');
INSERT INTO WINE_TYPE VALUES(245,'Mourvdre','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(246,'Mourvdre','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(247,'Mourvdre','White','Production');
INSERT INTO WINE_TYPE VALUES(248,'Mourvdre','White','Distribution');
INSERT INTO WINE_TYPE VALUES(249,'Mourvdre','White','Retail');
INSERT INTO WINE_TYPE VALUES(250,'Mourvdre','Red','Production');
INSERT INTO WINE_TYPE VALUES(251,'Mourvdre','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(252,'Mourvdre','Red','Retail');
INSERT INTO WINE_TYPE VALUES(253,'Petit Sirah','Rose','Production');
INSERT INTO WINE_TYPE VALUES(254,'Petit Sirah','Rose','Distribution');
INSERT INTO WINE_TYPE VALUES(255,'Petit Sirah','Rose','Retail');
INSERT INTO WINE_TYPE VALUES(256,'Petit Sirah','White','Production');
INSERT INTO WINE_TYPE VALUES(257,'Petit Sirah','White','Distribution');
INSERT INTO WINE_TYPE VALUES(258,'Petit Sirah','White','Retail');
INSERT INTO WINE_TYPE VALUES(259,'Petit Sirah','Red','Production');
INSERT INTO WINE_TYPE VALUES(260,'Petit Sirah','Red','Distribution');
INSERT INTO WINE_TYPE VALUES(261,'Petit Sirah','Red','Retail');
